export const qoutes = [
  "It does not matter how slowly you go as long as you do not stop.",
  "It always seems impossible until it's done.",
  "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.",
  "When something is important enough, you do it even if the odds are not in your favor.",
  "If you can dream it, you can do it.",
  "You will never win if you never begin.",
  "Always do your best. What you plant now, you will harvest later.",
  "Don't watch the clock; do what it does. Keep going.",
  "In order to succeed, we must first believe that we can.",
  "Problems are not stop signs, they are guidelines.",
  "You are never too old to set another goal or to dream a new dream.",
  "Be kind whenever possible. It is always possible.",
  "The past cannot be changed. The future is yet in your power.",
  "Never give up, for that is just the place and time that the tide will turn.",
  "The secret of getting ahead is getting started.",
  "Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step.",
  "Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.",
  "Setting goals is the first step in turning the invisible into the visible.",
  "When you reach the end of your rope, tie a knot in it and hang on.",
  "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.",
];
